config/routes.rb
Rails.application.routes.draw do
  resources :line_items
  post 'like' => 'likes#toggle'

  devise_for :users, controllers: {:registrations => 'users/registrations'}


  get :about, :to => 'pages#about'

  get :contact, :to => 'pages#contact'

  get :sell, :to => 'pages#sell'

  get :careers, to: 'pages#careers'

  get :blog, to: 'pages#blog'
  
  get :search, controller: :search

  resources :notifications do
    collection do
      post :mark_as_read
    end
  end


  resources :categories
  resources :subcategories
  
  get "buy", to: "products#buy"
  resources :stores do
    resources :products do
      resources :comments
    end

    post 'follow', :to => 'followings#create'
    delete 'unfollow', :to => 'followings#destroy'
  	get 'dashboard', to: "stores#dashboard"
    get 'settings', to: "stores#settings"
  end

  resources :orders

  resources :users, :only => [:show]
  root 'pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  
end

app/models/asset.rb
class Asset < ApplicationRecord
  belongs_to :product

  mount_uploader :image, AvatarUploader
end

app/models/category.rb
class Category < ApplicationRecord
  mount_uploader :avatar, AvatarUploader

  has_many :stores, dependent: :destroy
  has_many :subcategories, dependent: :destroy
  has_many :likes, as: :likeable, dependent: :destroy
  validates :name, presence: true, uniqueness: true 
  validates :avatar, presence: true

  extend FriendlyId
  friendly_id :name, use: :slugged

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/following.rb
class Following < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :store
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :likeable, polymorphic: true
end

app/models/notification.rb
class Notification < ApplicationRecord
	belongs_to :recipient, class_name: 'Store'
	belongs_to :actor, class_name: "User"
	belongs_to :notifiable, polymorphic: true

	scope :unread, ->{ where(read_at: nil) }
end

app/models/order.rb
class Order < ApplicationRecord
	has_one :product, dependent: :destroy
	belongs_to :store
end

app/models/product.rb
class Product < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged
  
  mount_uploader :image, AvatarUploader

  belongs_to :store
  belongs_to :subcategory, dependent: :destroy

  has_many :assets, dependent: :destroy
  has_many :likes, as: :likeable, dependent: :destroy
  has_many :comments, dependent: :destroy
  
  validates :name, :description, :price, presence: true
  validates :price, numericality: true
  validates :image, presence: true

  accepts_nested_attributes_for :assets, :allow_destroy => true

  before_save :round_price
  belongs_to :order, optional: true

  paginates_per 25

  # before_destroy :ensure_not_referenced_by_any_line_item

  private

  def round_price
    price.round
  end
end

app/models/search.rb
class Search
	
	attr_reader :term

	def to_partial_path
		'searches/show'
	end


	def initialize(options = {})
		@term = options.fetch(:term, "")
	end

	def products
		Product.where("name iLike?", search_term)
	end


	private

	def search_term
		"%#{term}%"
	end
end

app/models/store.rb
class Store < ApplicationRecord
  mount_uploader :avatar, AvatarUploader

  RESTRICTED_NAMES = %w[www]
  extend FriendlyId
  friendly_id :name, use: :slugged
  
  belongs_to :user, dependent: :destroy
  belongs_to :category, dependent: :destroy

  has_many :notifications, foreign_key: :recipient_id
  has_many :products, dependent: :destroy
  has_many :followings, dependent: :destroy
  has_many :followers, through: :followings
  has_many :orders, dependent: :destroy
  

  STORE_TYPES = ["Retailer", "Wholesaler", "Manufacturer"]

  validates :name, presence: true,
                  uniqueness: { case_sensitive: false},
                  format: { with: /\A[\w\-]+\Z/i, message: 'contains invalid characters'},
                  exclusion: { in: RESTRICTED_NAMES, message: 'restricted'}
  validates :description, presence: true
  validates :store_type, presence: true, inclusion: { in: STORE_TYPES }
  validates :category, presence: true

 

end

app/models/subcategory.rb
class Subcategory < ApplicationRecord
  mount_uploader :avatar, AvatarUploader

  belongs_to :category, dependent: :destroy
  has_many :products, dependent: :destroy

  extend FriendlyId
  friendly_id :name, use: :slugged
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :avatar, AvatarUploader


  has_one :store
  has_many :likes, dependent: :destroy
  has_many :followings
  has_many :followed_stores, through: :followings

  has_many :orders
  
  def following? store, user
    store.follower_ids.include? user.id
  end

  def follow (store, user)
    store.followers << user
  end

  def unfollow (store, user)
    store.followers.delete(user.id)
  end

  def toggle_like!(likeable)
    if like = likes.where(likeable: likeable).first
      like.destroy
    else
      likes.where(likeable: likeable).create!
    end
  end

  def likes!(likeable)
    likes.where(likeable: likeable).exists?
  end

  def buy(name, address, phone, email, store, product)
    if new_record?
      orders.where(name: name, address: address, phone: phone, email: email, store: store, product: product).create!
    end
  end

end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
	before_action :find_store, only: [:show, :update, :destroy]
	before_action :authenticate_user!, except: [:show]

	def index
		
	end
	def new
		@store = Store.new
	end

	def dashboard
		@store = Store.friendly.find(params[:store_id])
		@products = @store.products.order(created_at: "DESC").limit(5)
		# @orders = Order.where()
	end

	def show
		@store = Store.friendly.find(params[:id])
		@products = @store.products
		@meta_description = "#{@store.description}"
		set_meta_tags title: @store.name,
									site: 'Claeus',
									reverse: true,
									description: @store.description.truncate(200),
									twitter: {
										card: 'summary',
										site: '@claeusgh',
										title: "Check out my store, #{@store.name}",
										description: @store.description.truncate(200)
									},
									og: {
										title: "Check out my store, #{@store.name}",
										description: @store.description.truncate(200),
										type: 'website',
										url: store_url(@store),
										image: @store.avatar
									}
	end

	def create
		@store = Store.new(store_params)
		@store.user_id = current_user.id
		if @store.save
			redirect_to store_dashboard_path(@store), notice: "You have created your store successfully"
		else
			render 'new'
		end
	end

	def settings
		@store = Store.friendly.find(params[:store_id])
	end

	def destroy
		
	end


	private

	def find_store
		@store = Store.friendly.find(params[:id])
	end

	def store_params
		params.require(:store).permit(:name, :description, :user_id, :store_type, :category_id)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def flasherize(key)
		case key.to_sym
		when :error
			"error"
		when :success
			"success"
		else
			"alert"
		end
	end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/stores_helper.rb
module StoresHelper
	def follow_button store
		if  current_user && current_user != store.user 
			if current_user.following?(store, current_user)
				button_to 'Unfollow', store_unfollow_path(store), method: :delete, class: "follow-button"
			else
				button_to 'Follow', store_follow_path(store), class: "follow-button"
			end
		end
		
	end
end

app/views/stores/_form.html.erb
<%= form_with(model: store, local: true)  do |f| %>
	<% if @store.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@store.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
      <% @store.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
	<div class="form-group">
		<%= f.text_field :name, class: "form-input", placeholder: "Your store name", autofocus: true %>
	</div>

	<div class="form-group">
		<%= f.select :store_type, options_for_select(Store::STORE_TYPES), {},  class: 'form-input', placeholder: 'What type of seller? Eg. Retailer', include_blank: true %>
	</div>

	<div class="form-group">
		<%= f.collection_select :category_id, Category.order(:name), :id, :name, {}, include_blank: true, class: "form-input" %>
	</div>
	
	<div class="form-group">
		<%= f.text_area :description, cols: 10, rows: 3, class: "form-input", placeholder: "Describe your store/brand in 200 characters" %>
	</div>
	
	
	<%= f.submit "Create your store", class: "button button-bg " %>

<% end %>

<!-- <div class="modal">
  <label for="modal-1">
    <div class="modal-trigger">Click for Modal</div>
  </label>
  <input class="modal-state" id="modal-1" type="checkbox" />
  <div class="modal-fade-screen">
    <div class="modal-inner">
      <div class="modal-close" for="modal-1"></div>
      <h1>Modal Title</h1>
      <p class="modal-intro">Intro text lorem ipsum dolor sit ametm, quas, eaque facilis aliquid cupiditate tempora cumque ipsum accusantium illo modi commodi  minima.</p>
      <p class="modal-content">Body text lorem ipsum dolor ipsum dolor sit sit possimus amet, consectetur adipisicing elit. Itaque, placeat, explicabo, veniam quos aperiam molestias eriam molestias molestiae suscipit ipsum enim quasi sit possimus quod atque nobis voluptas earum odit accusamus quibusdam. Body text lorem ipsum dolor ipsum dolor sit sit possimus amet.</p>
    </div>
  </div>
</div> -->

app/views/stores/_settings.html.haml
.wrapper
	.card.large-card
		%h3 Edit your store

app/views/stores/dashboard.html.haml
.section
	.page
		%article.white
			.dashboard-container
				.wrapper
					.section-header= @store.name
					.row		
						.col-full
							.card.tiny-card
								.card-header 
									Performance
									%span= link_to "View your store", store_path(current_user.store), class: "button-sm button-main"
								
						.col-full
							.card.tiny-card
								.card-header 
									Products
									%span= link_to "New", new_store_product_path, class: "button-sm button-main"
									%span= link_to "View all", store_products_path, class: "button-sm button-main"
						
								.card-body
									- if @store.products.present?
									
										.pad-20
											.h4=	("You have #{@products.count} product").pluralize
											
											
											.store-products-thumbnails
												- @products.each do |p|
													.product-thumb{ style: "background-image:  url('#{p.image.url(:thumb)}')"  }
														
									- else 
										= button_to "List your first product", new_store_product_path, method: :get, class: "button button-sexy"

									

app/views/stores/modal.html.erb
<div class="modal">
  <label for="modal-1">
    <div class="modal-trigger">Click for Modal</div>
  </label>
  <input class="modal-state" id="modal-1" type="checkbox" />
  <div class="modal-fade-screen">
    <div class="modal-inner">
      <div class="modal-close" for="modal-1"></div>
      <h1>Modal Title</h1>
      <p class="modal-intro">Intro text lorem ipsum dolor sit ametm, quas, eaque facilis aliquid cupiditate tempora cumque ipsum accusantium illo modi commodi  minima.</p>
      <p class="modal-content">Body text lorem ipsum dolor ipsum dolor sit sit possimus amet, consectetur adipisicing elit. Itaque, placeat, explicabo, veniam quos aperiam molestias eriam molestias molestiae suscipit ipsum enim quasi sit possimus quod atque nobis voluptas earum odit accusamus quibusdam. Body text lorem ipsum dolor ipsum dolor sit sit possimus amet.</p>
    </div>
  </div>
</div>

app/views/stores/new.html.haml
.page
	%article.white	
		.wrapper
			.box
				.sell-title
					Get started by creating your store.
				.sell-form
					.section-header Fill in the form to start
					= render 'form', store: @store 

			-# .col-half
			-# 	.heading How to get noticed on Claeus

app/views/stores/settings.html.haml
= render(:partial => "settings")

app/views/stores/show.html.haml
.page-header
	.wrapper
		.store-header
			.store-header-content
				.row
					.col-full
						.store-info
							%h2.store-name= @store.name
							.badge.badge-alert= @store.store_type 
						.brand-desc= @store.description
						.followers
							= pluralize(@store.followers.count, "follower")
						.actions= follow_button (@store)
						.share-btns= social_share_button_tag(@store.name)
						

.section
	.store-pane
		.wrapper
			.row
				- @products.each do |p| 
					.col-quarter
						= link_to store_product_path(@store, p) do
							.card
								.card-image
									%img{:src => "#{p.image.url(:medium)}", :alt => ""}/
								.card-header
									.product-name= p.name.truncate_words(4) 
								.card-body
									.price= number_to_currency((p.price).to_i, unit: "GHS")
	    

								