config/routes.rb
Rails.application.routes.draw do
  resources :line_items
  post 'like' => 'likes#toggle'

  devise_for :users, controllers: {:registrations => 'users/registrations'}


  get :about, :to => 'pages#about'

  get :contact, :to => 'pages#contact'

  get :sell, :to => 'pages#sell'

  get :careers, to: 'pages#careers'

  get :blog, to: 'pages#blog'
  
  get :search, controller: :search

  resources :notifications do
    collection do
      post :mark_as_read
    end
  end


  resources :categories
  resources :subcategories
  
  get "buy", to: "products#buy"
  resources :stores do
    resources :products do
      resources :comments
    end

    post 'follow', :to => 'followings#create'
    delete 'unfollow', :to => 'followings#destroy'
  	get 'dashboard', to: "stores#dashboard"
    get 'settings', to: "stores#settings"
  end

  resources :orders

  resources :users, :only => [:show]
  root 'pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged
  
  mount_uploader :image, AvatarUploader

  belongs_to :store
  belongs_to :subcategory, dependent: :destroy

  has_many :assets, dependent: :destroy
  has_many :likes, as: :likeable, dependent: :destroy
  has_many :comments, dependent: :destroy
  
  validates :name, :description, :price, presence: true
  validates :price, numericality: true
  validates :image, presence: true

  accepts_nested_attributes_for :assets, :allow_destroy => true

  before_save :round_price
  belongs_to :order, optional: true

  paginates_per 25

  # before_destroy :ensure_not_referenced_by_any_line_item

  private

  def round_price
    price.round
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	before_action :set_product, only: [:edit, :update, :destroy]
	before_action :authenticate_user!, except: :show
	def show
		set_product
		@order = Order.new
		@comments = Comment.where(product: @product).order('created_at ASC')
		@meta_description = "#{@product.description}"
		set_meta_tags title: @product.name,
									site: 'Claeus',
									reverse: true,
									description: @product.description.truncate(200),
									twitter: {
										card: 'summary',
										site: '@claeusgh',
										title: @product.name,
										description: @product.description.truncate(200)
									},
									og: {
										title: @product.name,
										description: @product.description.truncate(200),
										type: 'website',
										url: store_product_url(@product),
										image: @product.image
									}
	end 

	def buy
		@product = Product.friendly.find(params[:product_id])
	end

	def index
		@store = Store.friendly.find(params[:store_id])
		@products = @store.products
	end

	def new
		@store = current_user.store
		@product = Product.new
		4.times { @product.assets.build }
	end

	def edit
		@store = Store.friendly.find(params[:store_id])
		4.times { @product.assets.build }
	end

	def create
		@product = Product.new(product_params)
		@product.store_id = current_user.store.id

		if @product.save
			 redirect_to store_dashboard_url(@product.store), notice: "Product added successfully"
		else
			 render 'new'
		end

	end

	def update
		respond_to do |format|
			if @product.update(product_params)
					format.html { redirect_to store_product_path([@store]), notice: 'Product was successfully updated.' }
					format.json { render :show, status: :ok, location: @product }
			else
					format.html { render :edit }
					format.json { render json: @product.errors, status: :unprocessable_entity }
			end
		end
	end

	def destroy
		set_store
		@product.destroy

		respond_to do |format|
			if @product.destroy
				format.html { redirect_to store_products_path, notice: 'Product Successfully deleted!!'}
			end
		end
	end

	private

	def set_store
		@store = Store.friendly.find(params[:store_id])
	end

	def set_product
		set_store
	 	@product = @store.products.friendly.find(params[:id])
	end

	def product_params
		 params.require(:product).permit(:name, :description, :price, :store_id, :image, :category_id, :subcategory_id, assets_attributes: [:image])
	end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: [@store, @product], local: true) do |f|%>
	<div class="row">

		<div class="col-half">
			<!--  -->
			<!--  -->
	    <div class="form-group">
	      <%= f.label "Select a Category" %>
	      <%= f.grouped_collection_select :subcategory_id, Category.order(:name), :subcategories, :name, :id, :name, {include_blank: true}, {class: "form-input"} %>
	    </div>

			 <div class="form-group">
				<%= f.label :name, class: "form-label" %>
				<%= f.text_field :name, class: "form-input" %>
			</div>

			<div class="form-group">
				<%= f.label :description, class: "form-label" %>
				<%= f.text_area :description, class: "form-input" %>
			</div>

			<div class="form-group">
				<%= f.label :price, class: "form-label" %>
				<%= f.text_field :price, class: "form-input" %>
			</div>

			<div class="form-group">
				<%= f.label :image, class: "form-label" %>
				<%= f.file_field :image, class: "form-input" %>
			</div>
		</div>
		<div class="col-half">
			<p class="lead">Add more pictures to this product</p>
			<div class="form-group">
				<%= f.fields_for :assets do |assets| %>
					<% if assets.object.new_record? %>
						<p>
							<%= assets.file_field :image, class: "form-input" %>
						</p>
					<% end %>
				<% end %>
			</div>
				<h3 class="section-header">Images
				</h3>

				<%= f.fields_for :assets do |assets| %>
					<%= link_to image_tag(assets.object.image.url(:thumb)), assets.object.image.url(:medium) %>
				<% end %>
		</div>
	</div>
   
	<p class="text-center"><%= f.submit id: "productSave" %></p>
<% end %>

app/views/products/edit.html.haml
.section
	.page
		%article.white
			.wrapper
				.section-header
					= "Edit " + @product.name
				= render "form", product: @product 

app/views/products/index.html.haml
.page
	%article.white
		.section
			.wrapper
				.section-header Your Products
				.row
					- @products.each do |p|
						.col-quarter
							= link_to store_product_path(@store, p) do
								.card
									.card-image
										%img{:src => "#{p.image.url(:medium)}", :alt => ""}/
									.card-header
										.product-name= p.name.truncate_words(4) 
									.card-body
										%p.price= number_to_currency((p.price).to_i, unit: "GHS")
	    

app/views/products/new.html.haml
.section
	.page
		%article.white
			.wrapper
				.section-header Add new product
				= render "form", store: @store

app/views/products/show.html.haml
.section
	.pdt-show
		.wrapper
			.product-header
				.image-container
					.product-img{ style: "background-image:  url('#{@product.image.url}')"  }

					.product-actions
						.actions-container
							- if user_signed_in?
								%span.action-like.action-showText
									= link_to like_path(product_id: @product.id), class: "#{'is-liked' if current_user.likes!(@product)}", method: :post do
										%span.fa.fa-heart.fa-2x{aria: {hidden: 'true'}}
										- if @product.likes.count > 0
											%span.showText= pluralize(@product.likes.count, "Like")
							- else
								%span.action-like.action-showText
									%span.fa.fa-heart.fa-2x{aria: {hidden: 'true'}}
									- if @product.likes.count > 0
										%span.showText= "#{@product.likes.count}"
							%br/
				.product-info
					.center-vertical-outer
						.center-vertical-inner
							.centered-section
								%span.badge-error= @product.subcategory.name
								
								%h1.product-name= @product.name
								.product-store
									%span  by
									= link_to @product.store.name, store_path(@product.store)
								.show-price= number_to_currency(@product.price, unit: 'GHS')

								-# .buy-now-container
								-# 	= form_for @order, url: orders_path(product_id: @product), local: true do |f|
								-# 		= f.number_field :quantity, value: 1, class: "form-input"

								-# 		= f.submit "Order now at #{number_to_currency(@product.price, unit: "GHC")}"  
									
								%br/
					.social-actions
						.actions-container	
							.social
								= social_share_button_tag(@product.name) 

							-# - if user_signed_in?
							-# 	= link_to new_user_registration_path, class: "comment" do
							-# 		Write a comment
							-# - else
							-# 	= link_to new_user_registration_path, class: "comment" do
							-# 		Sign up to comment

			.details
				.section-header Details
				.product-detail
					.product-detail-header 
						.header-title Gallery
					.product-assets
						- for asset in @product.assets 
							%li.asset= link_to image_tag(asset.image.url(:thumb)), asset.image.url
					
				.product-detail
					.product-detail-header
						.header-title Description
					.product-description= sanitize(@product.description)

				.comments-container
					= form_for [@product.store, @product,  @product.comments.build], remote: true do |f|
						-# = f.hidden_field :product_id, value: @product.id
						= f.text_area :body, class: 'form-input'
						= f.submit "Post comment"
					

				#comments
					= render @comments