config/routes.rb
Rails.application.routes.draw do
  resources :line_items
  post 'like' => 'likes#toggle'

  devise_for :users, controllers: {:registrations => 'users/registrations'}


  get :about, :to => 'pages#about'

  get :contact, :to => 'pages#contact'

  get :sell, :to => 'pages#sell'

  get :careers, to: 'pages#careers'

  get :blog, to: 'pages#blog'
  
  get :search, controller: :search

  resources :notifications do
    collection do
      post :mark_as_read
    end
  end


  resources :categories
  resources :subcategories
  
  get "buy", to: "products#buy"
  resources :stores do
    resources :products do
      resources :comments
    end

    post 'follow', :to => 'followings#create'
    delete 'unfollow', :to => 'followings#destroy'
  	get 'dashboard', to: "stores#dashboard"
    get 'settings', to: "stores#settings"
  end

  resources :orders

  resources :users, :only => [:show]
  root 'pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/asset.rb
class Asset < ApplicationRecord
  belongs_to :product

  mount_uploader :image, AvatarUploader
end

app/models/category.rb
class Category < ApplicationRecord
  mount_uploader :avatar, AvatarUploader

  has_many :stores, dependent: :destroy
  has_many :subcategories, dependent: :destroy
  has_many :likes, as: :likeable, dependent: :destroy
  validates :name, presence: true, uniqueness: true 
  validates :avatar, presence: true

  extend FriendlyId
  friendly_id :name, use: :slugged

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/following.rb
class Following < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :store
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :likeable, polymorphic: true
end

app/models/notification.rb
class Notification < ApplicationRecord
	belongs_to :recipient, class_name: 'Store'
	belongs_to :actor, class_name: "User"
	belongs_to :notifiable, polymorphic: true

	scope :unread, ->{ where(read_at: nil) }
end

app/models/order.rb
class Order < ApplicationRecord
	has_one :product, dependent: :destroy
	belongs_to :store
end

app/models/product.rb
class Product < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged
  
  mount_uploader :image, AvatarUploader

  belongs_to :store
  belongs_to :subcategory, dependent: :destroy

  has_many :assets, dependent: :destroy
  has_many :likes, as: :likeable, dependent: :destroy
  has_many :comments, dependent: :destroy
  
  validates :name, :description, :price, presence: true
  validates :price, numericality: true
  validates :image, presence: true

  accepts_nested_attributes_for :assets, :allow_destroy => true

  before_save :round_price
  belongs_to :order, optional: true

  paginates_per 25

  # before_destroy :ensure_not_referenced_by_any_line_item

  private

  def round_price
    price.round
  end
end

app/models/search.rb
class Search
	
	attr_reader :term

	def to_partial_path
		'searches/show'
	end


	def initialize(options = {})
		@term = options.fetch(:term, "")
	end

	def products
		Product.where("name iLike?", search_term)
	end


	private

	def search_term
		"%#{term}%"
	end
end

app/models/store.rb
class Store < ApplicationRecord
  mount_uploader :avatar, AvatarUploader

  RESTRICTED_NAMES = %w[www]
  extend FriendlyId
  friendly_id :name, use: :slugged
  
  belongs_to :user, dependent: :destroy
  belongs_to :category, dependent: :destroy

  has_many :notifications, foreign_key: :recipient_id
  has_many :products, dependent: :destroy
  has_many :followings, dependent: :destroy
  has_many :followers, through: :followings
  has_many :orders, dependent: :destroy
  

  STORE_TYPES = ["Retailer", "Wholesaler", "Manufacturer"]

  validates :name, presence: true,
                  uniqueness: { case_sensitive: false},
                  format: { with: /\A[\w\-]+\Z/i, message: 'contains invalid characters'},
                  exclusion: { in: RESTRICTED_NAMES, message: 'restricted'}
  validates :description, presence: true
  validates :store_type, presence: true, inclusion: { in: STORE_TYPES }
  validates :category, presence: true

 

end

app/models/subcategory.rb
class Subcategory < ApplicationRecord
  mount_uploader :avatar, AvatarUploader

  belongs_to :category, dependent: :destroy
  has_many :products, dependent: :destroy

  extend FriendlyId
  friendly_id :name, use: :slugged
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :avatar, AvatarUploader


  has_one :store
  has_many :likes, dependent: :destroy
  has_many :followings
  has_many :followed_stores, through: :followings

  has_many :orders
  
  def following? store, user
    store.follower_ids.include? user.id
  end

  def follow (store, user)
    store.followers << user
  end

  def unfollow (store, user)
    store.followers.delete(user.id)
  end

  def toggle_like!(likeable)
    if like = likes.where(likeable: likeable).first
      like.destroy
    else
      likes.where(likeable: likeable).create!
    end
  end

  def likes!(likeable)
    likes.where(likeable: likeable).exists?
  end

  def buy(name, address, phone, email, store, product)
    if new_record?
      orders.where(name: name, address: address, phone: phone, email: email, store: store, product: product).create!
    end
  end

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/stores_helper.rb
module StoresHelper
	def follow_button store
		if  current_user && current_user != store.user 
			if current_user.following?(store, current_user)
				button_to 'Unfollow', store_unfollow_path(store), method: :delete, class: "follow-button"
			else
				button_to 'Follow', store_follow_path(store), class: "follow-button"
			end
		end
		
	end
end

app/views/layouts/_footer.html.haml
%footer
	.wrapper
		.footer-container
			.footer-proper
				%h1.footer-tagline
					Discover awesome products on Claeus, <br>
					a community where emerging brands rule.
				.footer-primary-links
					= link_to "About", about_path
					= link_to "Sell", sell_path
					= link_to "Contact", contact_path
					= link_to "Blog", blog_path

				.footer-small-text
					Claeus is an independent company. 
					%br/
					©2017
					Claeus.co. All rights reserved.

				.footer-small-text.footer-secondary-links
					= link_to "Terms"
					= link_to "Privacy"
					= link_to "Copyright"
				.footer-social-links
					= link_to "Facebook"
					= link_to "Twitter"
					= link_to "Instagram"
			.footer-right.subscribe
				.subscribe-headline
					Get latest Claeus trends and ideas delivered right to your inbox.
				%br/
				.search-input-container
					.input-group
						= text_field_tag 'subscribe', nil, class: "form-input", placeholder: 'Enter your email'
						= submit_tag 'Go', class: 'input-group-button' 

app/views/layouts/_header.html.haml
.mainNav
	.mainNav-layout.wrapper
		.mainNav-tabs
			= link_to "Claeus", root_path, class: 'mainNavTab', id: 'logo'
		.mobileSearchContainer
			= form_with( url: search_path, method: :get, local: true) do |f|
				= f.text_field :q, class: "mobileNavSearch", placeholder: "Search products and stores", data: { behavior: 'autocomplete'}, id: "desktopSearchInput"
		.navUserSection
			.mainNav-userSection
				- unless current_page?root_path
					.mainNav-desktopSearchContainer
						.mainNavSearch-container
							= form_with( url: search_path, method: :get, local: true) do |f|
								= f.text_field :q, class: "mainNavSearch js-globalSearchInput", placeholder: "Search products, stores, tags ...", data: { behavior: 'autocomplete'}, id: "desktopSearchInput"
				
				- if current_page?root_path
					.nav-action.show-search{ style: 'display: none'}
				- else
					.nav-action.show-search

				.js-userNav.userNav
					- if user_signed_in?
						.nav-profile.nav-action.account-action{ style: "background-image:  url('#{current_user.avatar.url}')"  }
						.menuNav
							.menuNav-arrow
							.menuNav-scrim
							
							.menuNav-list
								= link_to "#{current_user.username}", user_path(current_user), class: "menuNav-item"
								- if current_user.store.present?

									= link_to "View store", store_path(current_user.store), class: "menuNav-item"

									= link_to "Admin Panel", store_dashboard_path(current_user.store), class: "menuNav-item"

								= link_to "Edit Profile", edit_user_registration_path, class: "menuNav-item"
								= link_to "Log Out", destroy_user_session_path, method: :delete, class: "menuNav-item"
						
					- else
						-# .menuNav-list
						= link_to "Start", new_user_registration_path, class: "join-button"
						-# = link_to "Login", new_user_session_path
				
						
						
			- if user_signed_in? && current_user.store.present?
				.notification-container
					.nav-action.nav-action-notifications{'data-behavior' => 'read-notifications'} 
						.closeNotifications
						.notificationsCount{data: {behavior: 'unread-count'} } 
						.notifications{'data-behavior' => 'notifications'} 
							.menuNav
								.menuNav-arrow
								.menuNav-scrim
								.menuNav-list{'data-behavior' => 'notification-items'} 
									
										
						

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Claeus - find products, stores and emerging brands across Africa."%></title>
    <% if @meta_description.present? %>
     <meta name=”description” content=”<%= @meta_description %>”>
    <% end %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= display_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro" rel="stylesheet">
  </head>
  <body>
    <div id="content">
      <%= render "layouts/header" %>
        <div class="wrapper">
          <br>
          <% flash.each do |key, value| %>
            <div class="flash-<%= flasherize(key)%>"><%= value %></div>
          <% end %>
        </div>
      <%= yield %>
      <%= render "layouts/footer" %>
    </div>
  </body>
</html>